### ISSUE TITLE
Command Line Arguments

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/calvin-network-tools#1]
In a perfect world: 
-- Configuration parameters are trumped by command-line arguments
-- Command args are parsed like this

command --command_arg=foo subcommand --subcommand_arg=bar

where things like --data are command args, and I guess something like runtime is a subcommand of `build`.  This is like git, and maybe supported with yargs and/or commander.

**Comment by jrmerz** [comment]
Can you give an example of where this is needed?  Might help me understand this issue.
