### ISSUE TITLE
Alternative to current location dump

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/calvin-network-tools#11]
Mui's current setup for dumping locations does not work.  When she tries to dump locations, only the first one is applied.  Without looking, I suspect that the dump may be going from the DB, while the edits are to the filesystem.  Doesn't really matter, basically, we need a plan to move these tools into this repo in a nice way.  One idea is that we replicate some of the PRM stuff, but with the native JSON formats.  In addition, think a a more standard editing capability.  

I'm thinking for example, if we end at just dumping JSON, than for command-line tasks,  we just use JQ, or other programs to do things like projections.  Editing, I'm not sure.  Looking for ideas.

**Comment by qjhart** [comment]
For example, this is what I did to get locations;

``` bash
echo "prmname,file,longitude,latitude" > ../mui.csv; 
for f in `find . -name node.geojson`; do
 jq -r "[.properties.prmname,\"$f\",.geometry.coordinates[]] | @csv" < $f; 
 done | sort >> ../mui.csv
```

**Comment by jrmerz** [comment]
Can you add some details about what tools she is currently using as well as what you mean by native JSON formats.

**Comment by qjhart** [comment]
By  currently using, I mean the information that you sent her for updating locations for nodes. @mclay120 , can you update with some exact calls that you make?

 My recollection is that is a set of two scripts:
- A script that will update the location of a node. This updates the filesystem. 
- A script that dumps all node locations to a CSV file. I think this uses the API connected to Mongodb

**Comment by qjhart** [comment]
By native JSON, I mean the actual JSON in the node.geojson or link.geojson files.   The only difference being that we can de-reference the $refs, to get the _full_ json, as in all the data.  I imagine that as something like:

nodejs ~/path/json --de-ref  A101 

but json is a terrible name.

**Comment by mclay120** [comment]
For updating locations, I followed the directions Justin showed me.    I
don't think we talked about what to do after I finished updating locations
or I forgot if we had.  I don't have any notes on that part.

Start database (:mongod), cd to working directory in new terminal, run
script and copy paste new location to the following command.  ctrl-c to
kill mongod when I'm done.  That's all the notes I got.

/Users/mclay/Documents/calvin/calvin-network-data/data/colorado-river/coachella/a507/node.geojson

Justins-iMac:ca-water-network mclay$ node lib/cmd -m node -f editLocation .
"U510" 32.786300,-115.561648 true

Justins-iMac:ca-water-network mclay$ node lib/cmd -m node -f editLocation .
"U508" 33.611261,-114.593351 true

Justins-iMac:ca-water-network mclay$ node lib/cmd -m node -f editLocation .
"A508" 33.456006,-114.681171 true

Quinn tried to help me export the updated node database with the following
command but it exported the original.

/Users/mclay/Documents/calvin/calvin-network-data/data/colorado-river/colorado-river/a508/node.geojson

Justins-iMac:ca-water-network mclay$ node lib/cmd -m network -f
dumpLocation >~/Downloads/muiLocationUA.csv

On Mon, Dec 7, 2015 at 5:36 PM, Quinn Hart notifications@github.com wrote:

> By currently using, I mean the information that you sent her for updating
> locations for nodes. @mclay120 https://github.com/mclay120 , can you
> update with some exact calls that you make?
> 
> My recollection is that is a set of two scripts:
> - A script that will update the location of a node. This updates the
>   filesystem.
> - A script that dumps all node locations to a CSV file. I think this
>   uses the API connected to Mongodb
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ucd-cws/calvin-network-tools/issues/11#issuecomment-162730168
> .

## 

::: (_(\
_: (=' :') :_
_.. (,(")(")¤°.¸¸._´¯`

**Comment by jrmerz** [comment]
I'm still confused.  Two things:
- node lib/cmd -m node -f editLocation... edit's the file system.  Then the file watcher updates the database. You should be able to checkin changes directly via git.
- Dump locations does dump from the database.  I believe that is marked in the docs: https://github.com/ucd-cws/calvin-network-app/tree/master/lib/cmd

Let me know what you are trying to accomplish and I can try and shed more light.

**Comment by mclay120** [comment]
The dump location does not contain the updated node location.

Here a few of the updated locations I did.   Except for the first point,
U101, the others are not updated in the dump file, attached.

Justins-iMac:~ mclay$ cd Documents/calvin/ca-water-network/
Justins-iMac:ca-water-network mclay$ node lib/cmd -m node -f editLocation .
"U101" 40.578266,-122.381293 true

success!

/Users/mclay/Documents/calvin/calvin-network-data/data/sacramento-river/northwest-valley/u102/node.geojson

Justins-iMac:ca-water-network mclay$ node lib/cmd -m node -f editLocation .
"U102" 39.929336,-122.176778 true

success!

/Users/mclay/Documents/calvin/calvin-network-data/data/sacramento-river/northwest-valley/u102/node.geojson

Justins-iMac:ca-water-network mclay$ node lib/cmd -m node -f editLocation .
"A102" 39.948533,-122.213994 true

success!

/Users/mclay/Documents/calvin/calvin-network-data/data/sacramento-river/northwest-valley/a102/node.geojson

Justins-iMac:ca-water-network mclay$ node lib/cmd -m node -f editLocation .
"SR-BLB" 39.813223,-122.340470 true

success!

/Users/mclay/Documents/calvin/calvin-network-data/data/sacramento-river/northwest-valley/sr-blb/node.geojson

Justins-iMac:ca-water-network mclay$ node lib/cmd -m node -f editLocation .
"A103B" 39.422885,-122.226513 true

success!

/Users/mclay/Documents/calvin/calvin-network-data/data/sacramento-river/central-basin-west/a103b/node.geojson

Justins-iMac:ca-water-network mclay$ node lib/cmd -m node -f editLocation .
"U103" 39.278912,-122.195831 true

success!

/Users/mclay/Documents/calvin/calvin-network-data/data/sacramento-river/central-basin-west/u103/node.geojson

Justins-iMac:ca-water-network mclay$ node lib/cmd -m node -f editLocation .
"U202" 39.278912,-122.195831 true

success!

/Users/mclay/Documents/calvin/calvin-network-data/data/sacramento-river/central-basin-east/u202/node.geojson

Justins-iMac:ca-water-network mclay$ node lib/cmd -m node -f editLocation .
"U201" 39.278912,-122.195831 true

success!

/Users/mclay/Documents/calvin/calvin-network-data/data/sacramento-river/southeast/u201/node.geojson

Justins-iMac:ca-water-network mclay$ node lib/cmd -m node -f editLocation .
"U104" 39.072219,-121.894600 true

success!

/Users/mclay/Documents/calvin/calvin-network-data/data/sacramento-river/central-basin-east/u104/node.geojson

Justins-iMac:ca-water-network mclay$ node lib/cmd -m node -f editLocation .
"A204" 38.781405,-121.596210 true

success!

/Users/mclay/Documents/calvin/calvin-network-data/data/sacramento-river/central-basin-east/a204/node.geojson

Justins-iMac:ca-water-network mclay$ node lib/cmd -m node -f editLocation .
"U204" 38.781405,-121.596210 true

success!

Justins-iMac:ca-water-network mclay$ node lib/cmd -m network -f
dumpLocation >~/Downloads/muiLocationUA.csv

On Tue, Dec 8, 2015 at 10:25 AM, Justin Merz notifications@github.com
wrote:

> I'm still confused. Two things:
> - node lib/cmd -m node -f editLocation... edit's the file system. Then
>   the file watcher updates the database. You should be able to checkin
>   changes directly via git.
> - Dump locations does dump from the database. I believe that is marked
>   in the docs:
>   https://github.com/ucd-cws/calvin-network-app/tree/master/lib/cmd
> 
> Let me know what you are trying to accomplish and I can try and shed more
> light.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ucd-cws/calvin-network-tools/issues/11#issuecomment-162969128
> .

## 

::: (_(\
_: (=' :') :_
_.. (,(")(")¤°.¸¸._´¯`

**Comment by qjhart** [comment]
@jrmerz , Mui can't update the github repo directly, because I am still getting new CalVIN models from Mustafa, and those are based on the current system.  I update that by exporting his SQL/DSS database into github ready format, and checking that in.  Part of what I do in that step is to read a CSV file, with Mui's locations, and assign those on import. That's why we need a separate file for that.  In retrospect, it would probably be better to have a patch file to capture any changes.  Or maybe have both.  But until we have everyone using calvin-network-data natively, we have this imprt problem.

**Comment by jrmerz** [comment]
@qjhart can you help summarize what needs to be done here?  Looking back on this issue it's hard for me to decipher.
