### ISSUE TITLE
Run the _north_ branch of the Calvin network tools

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/calvin-network-tools#14]
## north branch

To simplify the discussion, I've created a _north_ branch to the calvin-network-data.  This is to help show some of the things about scenarios we discussed.  Basically, I cloned the repo, created a new branch, deleted all the the northern section, fixed the sink.

``` bash
git clone https://github.com/ucd-cws/calvin-network-data.git
cd calvin-network-data
git checkout -b north
# Delete extraneous nodes 
git commit -a  
```

You can see this branch [here](https://github.com/ucd-cws/calvin-network-data/tree/51d1900b23f7f9bf0bc8163c373ad8a67807c261)

``` bash
# Add a new sink to C87
git commit -a 
```

You can see these relevant changes [here](https://github.com/ucd-cws/calvin-network-data/commit/098572c69d6e2de3de929f909c005f304acf4e1e) .  This is a good view to show all the changes made on that one node.
## Running the model.

If you want to run the hec-prm model for this same region, you should follow the directions from [network-tools](https://github.com/ucd-cws/calvin-network-tools).  

``` bash
git clone https://github.com/ucd-cws/calvin-network-data.git
(cd calvin-network-data; git checkout north)
```

This sets up the branch you want.  You can browse this, or switch branches, to see the master, or whatever.

``` bash
git clone https://github.com/ucd-cws/calvin-network-tools
cd calvin-network-tools && npm run init
```

This downloads the HEC runtime, and initializes your tools, so they point to the data repo you want.   Then to run the model.

``` bash
node nodejs/prm build --prefix=north
```

That builds the north.pri and northPD.dss and northTS.dss files.  Go ahead and investigate if you are interested.

``` bash
run=north; 
wine HEC_Runtime/hecprm.exe I=${run}.pri O=${run}.pro T=${run}TS.dss P=${run}PD.dss R=${run}.dss;
```

This runs the hecprm code, and you now have results in north.dss.  You can compare these to the flow.csv files in your input data, as they shouldn't change much.

**Comment by qjhart** [comment]
A few notes:
- [ ] Yes we should have a `node nodejs/prm run --prefix=north` command that runs the hecprm code for you, so you don't need to remember that context
- [ ]  We should have an `npm install -g` command for calvin-network-tools.  This should install the HEC_runtme into `/usr/local/lib/calvin-network-tools/HEC_Runtime`, and should also install `/usr/local/bin/prm`.  This would encourge more proper organization of the input/output files.
- [ ] In addition, we should have a program like `calvintool` that allows us to interogate that network.  We are working on that.
- [ ] We are working on the program to extract the info from the DSS output file more easily.   That would be another command-line tool, like `dss-tool`.  We have something like that now, but the interface is a bit wonky, since we didn't design it for general use.

**Comment by jdherman** [comment]
Confirmed to work on OSX! Very cool. Two quick things I ran into along the way --

1) After you clone the repo, you won't be able to see `north` in the output of `git branch` unless you use the `-a` flag. You can still `git checkout north`, though.

2) I had assumed that 

```
run=north; 
wine HEC_Runtime/hecprm.exe I=${run}.pri O=${run}.pro T=${run}TS.dss P=${run}PD.dss R=${run}.dss;
```

would be equivalent to 

```
wine HEC_Runtime/hecprm.exe I=north.pri O=north.pro T=northTS.dss P=northPD.dss R=north.dss
```

But that oddly seems not to be the case. The first way works, the second way just spits out a blank error file. Could be an OSX-specific issue.

**Comment by qjhart** [comment]
Super!  Yes, I have no idea why that second hecprm call doesn't work.  That makes no sense to me either.

Regarding git, we get different behaviors, that's not good.  On my machine, I get the behavior below.  The Initial clone pulls all branches, and the simple checkout goes back and forth , see the change in the number of directories in `data``.   I have a pretty generic ~/.gitconfig file, so I'm basically running standard git, version 2.6.2.

``` bash
quinn@cws-quinn:~/Downloads$ git --version
git version 2.6.2
[user]
    email = qjhart@ucdavis.edu
    name = Quinn Hart
[credential]
    helper = cache  --timeout=3600
[filter "lfs"]
    clean = git lfs clean %f
    smudge = git lfs smudge %f
    required = true
[http]
    cookiefile = /home/quinn/.gitcookies
[push]
    default = current
```

``` bash
quinn@cws-quinn:~/Downloads$ git clone https://github.com/ucd-cws/calvin-network-data.git
Cloning into 'calvin-network-data'...
remote: Counting objects: 52823, done.
remote: Compressing objects: 100% (1194/1194), done.
remote: Total 52823 (delta 521), reused 0 (delta 0), pack-reused 51390
Receiving objects: 100% (52823/52823), 88.29 MiB | 11.13 MiB/s, done.
Resolving deltas: 100% (19216/19216), done.
Checking connectivity... done.
quinn@cws-quinn:~/Downloads$ cd calvin-network-data/
quinn@cws-quinn:~/Downloads/calvin-network-data$ git branch -a -vv
* master                     fbff417 [origin/master] Updated with all location changes, some updates to flows.
  remotes/origin/HEAD        -> origin/master
  remotes/origin/S09I05      fbff417 Updated with all location changes, some updates to flows.
  remotes/origin/master      fbff417 Updated with all location changes, some updates to flows.
  remotes/origin/north       098572c Added rest of model as a sink on C87.
  remotes/origin/with-binary 5640ca8 Removed some old binaries.
quinn@cws-quinn:~/Downloads/calvin-network-data$ git checkout north
Branch north set up to track remote branch north from origin.
Switched to a new branch 'north'
quinn@cws-quinn:~/Downloads/calvin-network-data$ find data -type d | wc -l
105
quinn@cws-quinn:~/Downloads/calvin-network-data$ git checkout master 
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
quinn@cws-quinn:~/Downloads/calvin-network-data$ find data -type d | wc -l
3245
```

**Comment by qjhart** [comment]
@jdherman also, if you don't want to wait, I can send you a script that converts DSS to CSV.  The caveat is that it exports the entire DSS file, into a format that postgresql ready, where it stores the data in a single column as an array.  You need to put dssvue on your mac to use it, and it takes forever to run.

**Comment by jdherman** [comment]
Huh I did not know about the `-a` flag in `git branch`. My bad. I get the same behavior as you when I just run `git checkout north`, problem solved. I'll remove the comment above.

No, I'm happy to wait for a finalized version of the DSS reader. I was just excited to see that there is such a thing in the works, to go along with all of these other great tools.
