### ISSUE TITLE
CalvinTool Not in calvin-network-tools

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/calvin-network-tools#16]
Writing #15 has really got the juices going for me.  We've been thinking about what the difference between calvin and hobbes is, and I realize that if we were to do a few things to calvin, we would have a more more generic tool, that we really could say works for most everything.
- [ ] Include an overreaching geojson file that eliminates anything special about our directory structure.  We talked about this before.  And/or have a standard json directory walk methodology.
- [ ] Standardize on the JSON schema distribution 
- [ ] Add a `type` parameter for our "$ref" parameters, so we can include more than CSV.
- [ ] Create URIs from github repos for universal naming.  This would allow us to reference other datasets.

From this we could have general purpose mongodb ingestion, validation, reformatting, and github ready repos.

**Comment by jrmerz** [comment]
started https://github.com/ucd-cws/hobbes-network-format
