### ISSUE TITLE
Add 'run' to the prm commands.

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/calvin-network-tools#17]
Users should be able to automatically run the HECPRM code from the prm script.  Since the runtime parameter is already in the cnfiguration file that should be okay.  The output files, should be named with the same prefix as the --prefix parameter.

We could either pipe the output to the stdout, or capture that and report if the result is feasible or not.  I guess the former is best, as they already give a status.   Currently, the command I use for running the system is this: 

run=ggd6_ev; wine ~/calvin-network-tools/HEC_Runtime/hecprm.exe I=${run}.pri O=${run}.pro T=${run}TS.dss P=${run}PD.dss R=${run}.dss;

**Comment by jrmerz** [comment]
@qjhart give it a go local, not npm -g global version, but pull repo and try 'node nodejs/prm run --prefix test'.  If it looks good I will push to npm.  Note, most of the out put I am getting from hecprm.exe is streaming through stderr.  I am coloring the output red for all stderr.

**Comment by qjhart** [comment]
Looks good!  Close at will
