### ISSUE TITLE
Add --start and --stop to build sub-command

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/calvin-network-tools#2]
node prm --data=/home/quinn/calvin-network-data build --start=2010-01 stop=2013-10

builds a PRM file set limited to this range.  It does so by 
- Limiting all TS data to the specified range
- Modifying the initial capacities of the storage nodes.  This is done by replacing the initial and final storage conditions with the values in the stor.csv for the start and stop dates.

**Comment by jrmerz** [comment]
Ok, give it a go, obviously capacities are wrong, but ts dss file should be only for specified range

**Comment by qjhart** [comment]
Looks great! Storage.csv  now in place on latest pull of calvin-network-data.

**Comment by jrmerz** [comment]
@qjhart I'm not seeing any commits to calvin-network-data

**Comment by qjhart** [comment]
Sorry, try again.

**Comment by qjhart** [comment]
Stupidly limited this to build command.  
node prm --data=/home/quinn/calvin-network-data --start=2010-01 stop=2013-10 show sr_sha

should also show the same capacities as the build would create, of course.

**Comment by jrmerz** [comment]
the 'show' command only shows pri file snippets.  What affect should start and stop have with 'show'?

**Comment by qjhart** [comment]
If you are "Showing" a reservior, you want to make it match what happens when you "build", so you want to affect the initial and final storage conditions.

**Comment by jrmerz** [comment]
should be good to go.
