### ISSUE TITLE
String together prm commands 

### ISSUE THREAD

**Issue by jrmerz** [ucd-cws/calvin-network-tools#20]
We should be able to string together prm commands in one call.

ex:

```
 prm --prefix=wy2002dbg --debug=SR_GNT,SR_HID,SR_ML --start=2002-10 --stop=2003-09 build run
```

would build then run model.  
Splitting out from issue #18

**Comment by jrmerz** [comment]
@qjhart this was decently large update.  Please test.

**Comment by qjhart** [comment]
prm --prefix=wy2002dbg --start=2002-10 --stop=2003-09 --debug=SR_GNT,SR_HID,SR_ISB,SR_ML,SR_TL build
Running **Build** command.

Writing PRI file: /home/quinn/HEC/build.pri
Writing Penalty DSS file: /home/quinn/HEC/buildPD.dss
Trimming ts data: 10/1/2002 to 9/30/2003

This is building files called build,  not wy2002dbg :(

**Comment by jrmerz** [comment]
Looks like you are running from 'global/npm install' prm.  I have not updated npm.  All changes will initially be made to the repo until we have verified worked.  So:

git pull
node nodejs/prm .....

let me know if that's not the case.

**Comment by qjhart** [comment]
Yes, I was trying global, but ...

```
quinn@cws-quinn:~/HEC$ (cd ~/calvin-network-tools; git pull); node ~/calvin-network-tools/nodejs/prm --prefix=wy2002dbg --start=2002-10 --stop=2003-09 --debug=SR_GNT,SR_HID,SR_ISB,SR_ML,SR_TL build run
Already up-to-date.
Running **Build** command.

Writing PRI file: /home/quinn/HEC/build.pri
Writing Penalty DSS file: /home/quinn/HEC/buildPD.dss
```

**Comment by jrmerz** [comment]
pull and give it a go.

Some of the commands used to be spec'd as multiple, non-flagged arguments.  ex: node build foo.  This is being removed with the exception of the show & list commands.  I have tried to clean out the argument parsing, but you may see this again, let me know.
