### ISSUE TITLE
HEC_Runtime location

### ISSUE THREAD

**Issue by jrmerz** [ucd-cws/calvin-network-tools#21]
Currently the HEC_Runtime is stored inside the node module.  The problem is 'prm init' must be run every time 'npm install -g calvin-network-tools' is run as the module folder is removed.  What would be a better default place to install library folder (that works cross platform)?

**Comment by qjhart** [comment]
Argh Really?  Well I guess the first thing we need to do is decide how best to install nodejs. on a windows machine.  I see the following installation ideas:
-  http://blog.teamtreehouse.com/install-node-js-npm-windows
-  http://www.johnpapa.net/tips-for-running-node-and-npm-on-windows/
- http://abdelraoof.com/blog/2014/11/11/install-nodejs-without-admin-rights/

I'd say we go that last route, even though that gives us multiple nodejs installs? 
If you do that, than an install -g installs prm to your nodejs default location (in my case Z:/node_js/prm.exe) and then installs to $base/node_modules/calvin-network-data/.  

So, in that case prm init installs to that same location, and everything seems fine.

**Comment by jrmerz** [comment]
Part of this issue as been solved by 

``` Bash
prm update-library
```

Which will upgrade the nodejs code w/o removing the runtime.  Just need to figure out Windoz best practices...

**Comment by qjhart** [comment]
@jrmerz, I'm closing this issue, since I don't think it's the bottleneck in getting a windows installation to work.
