### ISSUE TITLE
Spaces in file path are not escaped

### ISSUE THREAD

**Issue by jrmerz** [ucd-cws/calvin-network-tools#29]
If the local folder, or it's path, have spaces, badness.

**Comment by jrmerz** [comment]
@msdogan ok, v1.0.31 has fixes for windows file paths.... though my vm decided it wanted to install 87 (yes, 87) windows updates while I was in the middle of testing.  So please let me know if things work.

**Comment by msdogan** [comment]
@jrmerz I am running the model with v1.0.30 and its at 400,000 iterations. I will check v1.0.31 for the next run. thanks.

**Comment by jrmerz** [comment]
@msdogan good to close?

**Comment by msdogan** [comment]
@jrmerz I didn't try this, but if you say it is working you can close the issue. I will open If I have any issues :)

**Comment by jrmerz** [comment]
sounds good
