### ISSUE TITLE
Consider adding hecprm.exe to the HEC_Runtime

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/calvin-network-tools#3]
Since we are only supporting 32-windows, this should be fine.  File found at  http://www.hec.usace.army.mil/software/hec-resprm/downloads.aspx 

in download: http://www.hec.usace.army.mil/software/hec-resprm/downloads/HEC-ResPRM_10_Setup.exe

**Comment by jrmerz** [comment]
So i have thought about this as well and I am torn.  I already feel bad we are hiding some of their jar's/dll's in 'our runtime'.  But under the badge of 'pain and suffering' (which is really what this library is trying to help with) I am ok with including what we have.

But if we are including parts of the HEC software package only for the sake of, you don't have to go to their website, seems like we should just be documenting the links above.  That way they keep as much visible attribution (and traffic tracking) as possible.

**Comment by jrmerz** [comment]
*ok, I, see this is just cause the installer is a .exe?

**Comment by qjhart** [comment]
Correct, and actually running the hecprm via command-line is completely hidden.  We discussed a bit yeasterday, and the inclination is to provide it, but verify that's okay.

**Comment by jrmerz** [comment]
Added to runtime zip
