### ISSUE TITLE
Need to expose the hobbes-network-format --reindex command to prm

### ISSUE THREAD

**Issue by jrmerz** [ucd-cws/calvin-network-tools#30]
Whenever edits are made to the underlying calvin-network-data repos, the hnf --reindex command needs to be run.  This command should be exposed as part of the prm tool as well.

**Comment by jrmerz** [comment]
for now, you can run:

``` bash
npm install -g hobbes-network-format
hnf --directory /path/to/calvin-network-data/data --reindex
```

**Comment by msdogan** [comment]
@jrmerz I run above commands, but now I got the attached error.
[error.txt](https://github.com/ucd-cws/calvin-network-tools/files/348676/error.txt)

**Comment by jrmerz** [comment]
I push pushed v1.0.32 which has a --reindex flag.  Can you run 

``` bash
prm update-library
prm build --prefix test --reindex
```

and let me know the results

**Comment by msdogan** [comment]
@jrmerz I still get the same error, possibly about UBM.csv, attached here.
[error_reindex.txt](https://github.com/ucd-cws/calvin-network-tools/files/348750/error_reindex.txt)
Update: I get that error without `--reindex` flag as well `(prm build --prefix test)`

**Comment by msdogan** [comment]
@jrmerz I have installed v1.0.33 but still get the error. Error and .prmconf are attached (zipped) (Just to let you know, I deleted node Sink_C41, and I am running `prm build --prefix test --reindex` after that.
[Z.zip](https://github.com/ucd-cws/calvin-network-tools/files/350568/Z.zip)

**Comment by jrmerz** [comment]
@msdogan verified working.  closing for now.  Open if issues arise.
