### ISSUE TITLE
Nulls for initialstorage and endingstorage

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/calvin-network-tools#31]
If a node.geojson file has a null value for these, they should just not write anything, not a NAN.

**Comment by jrmerz** [comment]
fix pushed in repo. Let me know if working and I will push to npm.

**Comment by msdogan** [comment]
@jrmerz @qjhart I tried only for SR_BVLB. I changed ending storage value to 'null' and it was 'NaN' in the .pri file. But HEC-PRM didn't like it. It ended with an error message. After I deleted 'NaN', it run.

**Comment by jrmerz** [comment]
@msdogan did you run with the 'prm' command or from the calvin network repo (command would look like 'node ./nodejs/index.js build --prefix')?  Because I have not pushed a new version of prm with this fix, was waiting for verification first.

**Comment by msdogan** [comment]
Oh I thought you pushed to calvin-network-tools repo. Then, no. I run `prm build --prefix test` and it was 'NaN' there

**Comment by jrmerz** [comment]
So let's add some clarifying language.  This code repo, we will call the 'GitHub Repo', the global **prm** command we will call 'npm'.  So the fix was pushed to the GitHub repo (accessible via 'git pull') but not published to npm (accessible via 'prm update-library'). 

I will push a new version to npm.  Let me know if it works.

**Comment by jrmerz** [comment]
k, npm has been updated to version v1.0.35

**Comment by msdogan** [comment]
Sorry @jrmerz , I thought they are the same thing :) I will update and give it a try.

**Comment by jrmerz** [comment]
@msdogan no worries, I was kinda guessing that and wanted to clarify so we are all talking the same 'lingo' :)

**Comment by msdogan** [comment]
@jrmerz I think it is working fine. I checked only for SR_BVLB, which has a 'Null' in endingstorage in calvin-network-data/data and 
`prm build --prefix test` command does not put anything in .pri file as we want.

**Comment by jrmerz** [comment]
@msdogan ok to close then?

**Comment by msdogan** [comment]
yes, we can close this. It is working.
