### ISSUE TITLE
Inactive links and Inflow links issue for Matrix Export

### ISSUE THREAD

**Issue by msdogan** [ucd-cws/calvin-network-tools#32]
@qjhart @jrmerz when exporting network matrix with command `cnf matrix --format csv --start 2002-08 --stop 2002-10 --ts . --to network --max-ub 1000000 --outnodes node` there are two issues identified:
- Cost (c) and Amplitude (a) values for inflow links are flipped. Example: `INFLOW.2002-09-30   SR_HTH.2002-09-30      0    1   0   4.099832    4.099832
  ` First value after link name is k, then cost, amplitude, lower_bound and upper_bound. So, cost should be zero instead of 1, and amplitude should be 1 instead of zero.
- Links with zero upper bound are not included in the matrix, which causes mass balance problem while running the model.

**Comment by jrmerz** [comment]
pushed to npm @ v1.0.36

**Comment by msdogan** [comment]
@jrmerz this is verified working.
