### ISSUE TITLE
Connecting Desal to Source node in matrix export

### ISSUE THREAD

**Issue by msdogan** [ucd-cws/calvin-network-tools#37]
@jrmerz `desal` nodes are not connected to `source` node. water should come from the source. Without connecting to source node, mass balance constraint complains about it. There is a link from `desal` to `sink`. I don't know the purpose of that link. I think there should be only a link or links from main source node to desal node and then desal node to urban areas, which are already in the matrix.

**Comment by msdogan** [comment]
okay, I see why we have a sink link for desal node. We have a constrained inflow 10,000 TAF to desal node, and the sink link takes what is not being used. However, `INFLOW to desal` does not show up in the matrix export.
https://github.com/ucd-cws/calvin-network-data/tree/master/data/desal

**Comment by jrmerz** [comment]
@msdogan so I am a little confused here.  To answer the question about INFLOW not showing up on the Desal node, this is because **flow** is null.  Currently there has to be a flow to generate inflow.  We made an exception to this in issue #33 where there is no flow to another node instead is a direct flow to a sink.  Is this a similar condition?

As for Desal not connected to a SOURCE node.  This lack of inflow appears to be preventing the creation of a SOURCE link.

**Comment by msdogan** [comment]
@jrmerz I thought `flow` shows the feasible flows from previous run (output), and inflow is represented with `inflows`. Am I right? There is `inflows\default.csv` for inflows.

Here is the `desal\node.geojson`

```
{"type":"Feature",
 "geometry":{"type":"Point","coordinates":[-123.285448,33.02656]},
 "properties":{"prmname":"Desal",
 "description":"Proposed desalination facility for coastal cities",
 "type":"Junction",
 "inflows":{"default":{"description":"Ocean desalination","inflow":{"$ref" : "inflows/default.csv"}}},
 "sinks":[{"default" : {"description" : "Desalination excess flows", "costs" : {"type":"Constant",
 "cost":0}, "bounds" : [{"type":"NOB"}], "flow" : {"$ref" : "./sinks/default/flow.csv"}}}],
 "flow":null}}
```

Update: I haven't looked at exported matrix yet for desal, I am just looking at data right now. https://github.com/ucd-cws/calvin-network-data/tree/master/data/desal

**Comment by jrmerz** [comment]
Yes, but the dates investigated by the code, by this I mean we create a iterable array of dates and then use the array to add links to sinks, storage, inflows etc based on this array.  Currently this array of dates is generated using the **flows** timeseries data.  So if no flow then no sinks, storage or inflow will be generated except for exception stated above.

So with that in mind, I'm trying to figure out if this is a implementation bug or a logical reason for the dependency on flow and we need to be careful how we implement this second exception.   @qjhart Perhaps you can shed some light here?  Best way to move forward?

Sorry of this response is confusing, I can try an clarify further if you want.

**Comment by msdogan** [comment]
This is a little different than what I thought. So, there has to be **flows** to run the model, but if we are running for the first time, we can't do that :) But, for CALVIN it is okay I guess

**Comment by msdogan** [comment]
I can think of another set up similar to `desal` is `CN2` https://github.com/ucd-cws/calvin-network-data/tree/master/data/sacramento-river/southeast/cn2
For the node CN2 there is `flows.csv` I wonder why it is null for desal

**Comment by msdogan** [comment]
And regarding your fix @jrmerz, it does not seem to solve the inflow issue for desal in `v1.0.44`. There is still no INFLOW to desal link.

**Comment by jrmerz** [comment]
@msdogan I have not submitted any fixes for this issue.  v1.0.44 was submitted as a fix for issue #33 which you verified and closed.

**Comment by msdogan** [comment]
Sorry @jrmerz, I thought that fix also included this issue.

**Comment by msdogan** [comment]
@qjhart @jrmerz looks like it is not only desal node that has no incoming links. Here is other nodes without incoming links, which results in mass balance issues:

```
C146, C148, C304, C86, D43a, Desal
```

**Comment by jrmerz** [comment]
@msdogan sorry for the delay on this.  I have to admit, re-reading this issue I am still a little lost on solution.  This seems like a data issue, no?

For example, C146 specifically has a timeseries info set to 0: https://github.com/ucd-cws/calvin-network-data/blob/master/data/colorado-river/coachella/c146/inflows/default.csv

**Comment by msdogan** [comment]
@jrmerz I agree with you. Since we don't know what is causing this, it might be better to modify calvin-network-data and send pull request. I guess we need to add flow.csv files to those nodes and update node/link.geojson. I don't know how those flow.csv is calculated, but I am guessing for this case, it would be the same as inflow.csv, right?

**Comment by jrmerz** [comment]
I'm a little confused, the inflow.csv provided above is 0.

**Comment by msdogan** [comment]
@jrmerz it is fine. The inflow above is New or Alamo river is so Cal that its water is not good for water supply, so its inflow is all set to zero. There is a few more time series with zero flows like this.

**Comment by jrmerz** [comment]
In investigation of node C86, where there is inflow data, but no inflow in the matrix, the issue is the same as #33 .  The timeseries 'steps' for inflow are dictated by the flow, but since there is no flow, the inflow is ignored.  @msdogan @qjhart @jdherman Please advise on how you would like to proceed.

https://github.com/ucd-cws/calvin-network-data/tree/master/data/sacramento-river/northeast-valley/c86

**Comment by msdogan** [comment]
@jrmerz I was thinking to add missing 'flow' time series manually for those nodes. But I am not sure how those flow time series were calculated for HOBBES.

**Comment by jrmerz** [comment]
@msdogan ok, its coming clearer now.  Sorry, I didn't totally understand your comment on this before but now I think I do.  Just let me know when you decide how to proceed.

**Comment by msdogan** [comment]
@jrmerz no worries, I will be working on this after September 4th.

**Comment by msdogan** [comment]
@jrmerz I am getting more confused about this 'flow.csv' files because there are more missing inflow links in the matrix export than the list above because a node does not have a 'flow.csv' file. Example: 

https://github.com/ucd-cws/calvin-network-data/tree/master/data/sacramento-river/northeast-valley/c87

Could you please explain to me how those 'flow.csv' files are calculated and their purposes for nodes and links? Why do we have 'flow.csv' for nodes and links?

Also, how hard is to update time period info not to get from 'flow.csv. file. As far as I understand, time period is read from 'flow.csv' and if it is missing, no data is written. Am I wright?

Thanks,

Note: example is updated

**Comment by whiteellie** [comment]
@msdogan, you wrote: "Those csv files created for nodes and links based on FLOW_DIV(KAF) in the HEC-PRM output file. For links this represents flow deliveries (diversion), but for nodes I do not know what it represents." 

I checked the test output dss file, and it seems like the FLOW_DIV for nodes is the sum of all diversions from that node (excluding link to debug) exp.U102. in non debug mode of course this value would be equal to FLOW_IN, so there's no need to calculate it. 

The prm manual has confused us by defining it as: "Flow diverted from this node. It is stored with pathname part B containing the "from" node and the "to" node identifiers separated by a "-" character." The first sentence is what hobbes is doing and the second sentence is what both hobbes and calvin are doing.

**Comment by msdogan** [comment]
Thanks @whiteellie , that was one part of the issue, the other part is missing `FLOW_DIV` data for nodes. We still don't know why HECPRM does not calculate it for all nodes. Does it say anything about that in the manual?

**Comment by whiteellie** [comment]
@msdogan Only thing I have seen about it is that it may be a displaying issue not a calculating issue. There must be somewhere where you get to tell PRM what to put in the output dss file. no? I will look at the manual more this afternoon and update if I see anything.

**Comment by jrmerz** [comment]
Ok, tested inflows added.  Please verify.

**Comment by msdogan** [comment]
@jrmerz yes, verified, inflows are in the matrix, except for `C146` and `C148` Do you have any idea why? As far as I remember, inflow time-series for these two are all zeros. Could this be the reason why the script does not create inflow links for `C146` and `C148`?

**Comment by jrmerz** [comment]
@msdogan So the current code is explicitly ignoring undefined, null and 0 inflow values:
https://github.com/ucd-cws/calvin-network-tools/blob/extrapolated-cost/nodejs/matrix/inflows.js#L28

I can change that if you would like.

**Comment by msdogan** [comment]
I am voting for changing the code for '0 inflow' case. @jdherman do you see any problem with that?

**Comment by msdogan** [comment]
I am voting for change because for some time-steps, there are 0 inflows. Below is an example. for those time steps, the code probably won't generate inflow link. This does not change results but it creates mass balance problems if inflow is the only incoming link.
`Local Inflow to C5`

```
    C5
    FLOW_LOC(KAF)


    KAF
    PER-AVER
31Oct1921   0.00
30Nov1921   1.80
31Dec1921   37.30
31Jan1922   0.00
28Feb1922   129.10
31Mar1922   0.00
30Apr1922   0.00
31May1922   0.00
30Jun1922   0.00
31Jul1922   0.00
31Aug1922   0.00
30Sep1922   0.00
31Oct1922   0.00
30Nov1922   0.00
31Dec1922   8.70
31Jan1923   0.00
28Feb1923   17.20
31Mar1923   0.00
30Apr1923   78.30
31May1923   0.00
30Jun1923   5.50
31Jul1923   0.00
```

**Comment by jdherman** [comment]
I agree, let's have the 0 inflows included in the matrix. We might want to change them later, and it helps to see the full time series. Thanks guys.

(The undefined/null ones are more of a problem, that's a different issue).

**Comment by jrmerz** [comment]
Ok, pushed.  Let me know how this look.

**Comment by msdogan** [comment]
thanks @jrmerz it looks good. Closing the issue. For now only remaining thing for matrix export is cost values for SR_SHA and SR_CLE.
