### ISSUE TITLE
Get Node and Link Order for PRI output to match Netbuilder output if possible

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/calvin-network-tools#38]
We could do a better comparison of the two files if we could compare them more directly.  The easiest method for this would be to match the orderr of the output.  We think that PRM builder uses alphbetical order.   Can we have PRM match that same output?  The most important comparison if S09I05.pri

**Comment by jrmerz** [comment]
Example netbuilder file?

**Comment by qjhart** [comment]
S09I05.pri Do you have these

**Comment by jrmerz** [comment]
yup

**Comment by jrmerz** [comment]
@qjhart pushed first set of changes.  I have sorted alphabetical order.  There are a lot of small formatting tweaks that are required to get an exact match with the Netbuilder file.  Some of these are actual floating point precision issues.  Others are strange, like trimming string after ending storage for nodes.  I have only attacked the NODE DEFINITIONS for these more 'unique' tweaks.  let me know your thoughts.

FYI, Github seems to be missing some comments....

**Comment by qjhart** [comment]
I cleaned up the comments, and added that example to the original issue.  Regarding the other items w.r.t  the netbuilder file.  Those are all things that we will not worry about.  Mostly, they want to see the order.  I told them, they would probably have to postprocess to eliminate some differences like DSS naming, descriptions, etc.  SO i think we are good, and I'm closing for now.
