### ISSUE TITLE
KAF vs. CFS in time-series DSS file

### ISSUE THREAD

**Issue by msdogan** [ucd-cws/calvin-network-tools#39]
@jrmerz 
We don't know if this is just a labeling issue or HEC-PRM makes some conversion. All units in time-series DSS file for base CALVIN (S09I05TS.DSS) is KAF (TAF). But, although numbers are the same, test run generated from HOBBES thinks that those are CFS. This is true for all time-series in testTS.DSS file. This is probably a issue when writing DSS file from HOBBES database. Based on yesterday's discussion, although this may not change results, it might be confusing for other people. Below is an example:
(Blue is CALVIN (S09I05) and red is HOBBES test run)
![taf-cfs](https://cloud.githubusercontent.com/assets/14085662/18721112/cd84cf56-7fe3-11e6-8c91-ef5cb8d255f2.jpg)

**Comment by jrmerz** [comment]
Nice catch. Looks like CFS is the default.  I was accidentally setting 'xunits' instead of 'units' in the code for those.  Just pushed a new version.  Give it a look calvin-network-tools@1.0.46

**Comment by msdogan** [comment]
it looks good, thanks!
