### ISSUE TITLE
prm build  PD files really need a dummy input

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/calvin-network-tools#4]
Not sure if the hecprm will fail, but does throw an error.  The dummy PD in current are: 

![image](https://cloud.githubusercontent.com/assets/344953/11196329/28154850-8c6b-11e5-944f-ca4e00c857d2.png)

**Comment by jrmerz** [comment]
Clarification.  Does this mean add this dummy data to the pd dss file by default?

**Comment by jrmerz** [comment]
Added here: eac1666af5df15ae01db44cb04a5e8f158f2bbf6
