### ISSUE TITLE
--node flag not working

### ISSUE THREAD

**Issue by jrmerz** [ucd-cws/calvin-network-tools#47]
I used to export the matrix only for defined nodes not for whole network with the flag nodes SR_SHA D5, which does not seem to work. Is there a way to export the matrix only for defined nodes?

(split from issue #46 )

**Comment by jrmerz** [comment]
@msdogan so there are a couple things here.  First, it you want to have a subnet of nodes/linkes, you just provide the prmnames at the end of the command:

```
cnf matrix --verbose --format=csv --start=2002-01 --stop=2003-01 --ts=. --to=network --max-ub=1000000000 SR_SHA D5 
```

Next, there was a issue where the new HOBBES tools expected the new HOBBES 'full path' identifiers.  Since we haven't switched to these yet, I have added functionality so the calvin-network-tool can define which identifier to split on.  What this means... you can again use (in fact you must use) CALVIN prmnames as identifiers to split on.

All changes have been pushed at calvin-network-tools@2.0.5

**Comment by msdogan** [comment]
@jrmerz I used the above command but it still exports the whole network not the defined subset

**Comment by jrmerz** [comment]
Humm, might have to get on a screenshare for this one, I have retested and export matrix is correct on my machine.   Which OS?

**Comment by msdogan** [comment]
I am using Windows 7.

command line:
```
AD3+msdogan@CWS-Amargosa  /z/calvin-network-tools (master)
$ cnf matrix --verbose --format=csv --start=2002-01 --stop=2003-01 --ts=. --to=network --max-ub=1000000000 SR_SHA D5
*** CNF Arguments ***
  _allowUnknownOption: false
  _name: matrix
  _noHelp: false
  _description: Create a network matrix
  format: csv
  header: true
  start: 2002-01
  stop: 2003-01
  ts: .
  to: network
  maxUb: 1000000000
  data: z:\calvin-network-data\data
  runtime: Z:\nodejs\node_modules\calvin-network-tools\HEC_Runtime
  verbose: true
[ 'SR_SHA', 'D5' ]
**********************

Running matrix command.

Matrix export complete.

AD3+msdogan@CWS-Amargosa  /z/calvin-network-tools (master)
```

output matrix screenshot:

<img width="1440" alt="screen shot 2017-01-03 at 12 54 55 pm" src="https://cloud.githubusercontent.com/assets/14085662/21622753/eebe3712-d1b3-11e6-8602-df6298bfd750.png">

**Comment by msdogan** [comment]
worked after the command `npm install -g calvin-network-tools`
