### ISSUE TITLE
export spatial subset

### ISSUE THREAD

**Issue by jdherman** [ucd-cws/calvin-network-tools#52]
@jrmerz  in an effort to take advantage of your last days on the job ...... :)

we were wondering how big of an effort it would be to enable something like this:

```
cnf matrix --format csv blah blah blah --region sacramento-river
```

I thought it might be doable since the folder structure is already grouped into regions, which could simplify things. The tricky part I'm guessing is the boundary conditions -- similar to the time subset that Mustafa is working on now.

No worries if it's too far off to think about right now, we were just curious.

**Comment by jrmerz** [comment]
push to NPM calvin-network-tools@3.0.3

Quick notes.
 - flag is ```--regions```
 - ```--verbose``` will dump the nodes in the subnet so you can know what is being included
 - you can comma separate multiple regions 
 - for sub regions, it's recommend you specify entire path ```--regions sacramento-river/northwest-valley```, though ```--regions northwest-valley``` will work, it will match to any region id that ends with northwest-valley

Let me know how that looks or questions/comments

**Comment by jdherman** [comment]
Wow, this is awesome, thanks!! We shall test .... along with the "time subset" that Mustafa is working on now. If we can get both of those running in the solver, we'll be good to go.

I'll close this now and open a new issue if we run into anything. Thanks again Justin.

**Comment by jdherman** [comment]
@jrmerz last thing :)  is it possible to do this regional export using the old naming convention -- just the node names instead of the full paths? Not by default but maybe a flag option.

**Comment by jrmerz** [comment]
@jdherman So this would be some work.  Splitting the network is actually a function of the HOBBES code.  HOBBES only knows the full network path identifiers, it is unaware of the prmnames, or any other property of a node/link.

**Comment by jdherman** [comment]
Ah ok thanks. Is there any option in the reverse direction -- to output the full HOBBES path when exporting the full network (not a regional subset)? 

Our postprocessing scripts use the prmnames, which is why I'm asking. We could figure out how to change them, we just have to be consistent either way.

I know you're officially done now so no pressure to keep up with this stuff. This was the last question that came up last week.
