### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/calvin-network-tools#6]
`node nodejs/prm build --data ~/calvin-network-data/data all`
- [x] Inflows are of type INFL not INFLOW
- [x] The inflows descriptions are missing. 
- [x] No newlines without '^..'  (After IN line)

```
# Ours
LINK      INFLOW    SOURCE    GW_SC     1.000     0.000                                   
LD                                                                                        
IN        A= B=GW_SC C=FLOW_LOC(KAF) D= E=1MON F=default

..

# Theirs
LINK      INFL      SOURCE    GW_SC     1.000     0.00                
LD        Santa Clara + Niles Cone + Livermore Groundwater Recharge
IN        A=HEXT2014 B=SOURCE_GW-SC C=FLOW_GW(KAF) E=1MON F=SANTA_CLARA_GEN
..        
```

```
```
- [x] Time series are off by one month.  Eg. calvin-network-data/data/central-coast/northern/gw_sc/inflows/default.csv starts with 

```
date,kaf
1921-10-31,9.868088
```

![image](https://cloud.githubusercontent.com/assets/344953/11349180/9ba5bd3a-91df-11e5-9690-ce9c31865590.png)

But allTS.dss thinks starts in 1921-11-31
- [x] CSV imports don't respect scientific notation.  I think this just came up, and could be modified in input CSV files, but makes sense to support. 

EG: 

```
quinn@cws-quinn:~/HEC$ cat ~/calvin-network-data/data/sacramento-river/central-basin-west/ud_yuba/hxi201-ext_yuba/costs/JAN.csv 
capacity,cost
0,0.01
1e-06,0

```

![image](https://cloud.githubusercontent.com/assets/344953/11349340/91512634-91e0-11e5-8a2b-64cdc5935403.png)

This looks OKAY (eg 0.00001 in DSS supplied by mustafa)
![image](https://cloud.githubusercontent.com/assets/344953/11349843/30f328f2-91e3-11e5-9c3f-3fdbb03e6773.png)

**Comment by jrmerz** [comment]
Make sure and download the v1.3 runtime.
