### ISSUE TITLE
HGR08 near CVPM region 8 creating problem in cookie cut

### ISSUE THREAD

**Issue by mlmaskey** [ucd-cws/calvin-network-tools#63]
@nickrsan and @msdogan 
As I mentioned in the previous issue on cookie cut for Folsom Dam, [Cookie Cut  #62 ], I got failed with the error message posted [there](https://github.com/ucd-cws/calvin-network-tools/issues/62). Then, I also tried with only two links, one with GW_08 and another with EXT_SAC. In both cases, adding HGR08 created the problem in the importing matrix. The error messages for both cases are similar to what I got before, and it is posted here as well. Could you please have any suggestions if it is the case? 

First effort: This is the case posted in issue #62 

`cnf matrix --format csv --start 1921-10 --stop 1922-10 --ts . --to linksWY1922 --max-ub 1000000000000 --debug all --verbose D17 SR_FOL D9 C173 HGP08 A207 CVPM08G HGR08 GW_08 CVPM08S HSU207C173 HU207 HSD207 WTP207 U207 D517 C107 D85 D64 C67 HSU204C67 HGP07 A204 CVPM07G HGR07 GW_07 CVPM07S C7 C18 C19 C16 WTP205 C20 C8 C104 C105 HXI204 HNP204 HP204 HSD204 HSU204C67 HU204 WTP204 WWP204 U204 EXT_SAC INT_SAC D44 D503 D511 D513 D55 HSU_D55 D507 D509 PMP_ISOL_F`

Second effort
`cnf matrix --format csv --start 1921-10 --stop 1922-10 --ts . --to linksWY1922 --max-ub 1000000000000 --debug all --verbose GW_08 HGR08`

Third effort:
`cnf matrix --format csv --start 1921-10 --stop 1922-10 --ts . --to linksWY1922 --max-ub 1000000000000 --debug all --verbose EXT_SAC HGR08`

Messege for both cases:

```
(base) D:\PostDocResearch\UC Merced\importCALVIN\NOAA\runBase>cnf matrix --format csv --start 1921-10 --stop 1922-10 --ts . --to linksWY1922 --max-ub 1000000000000 --debug all --verbose EXT_SAC HGR08

*** matrix Input Parameters ***
{
  "_": [
    "matrix"
  ],
  "help": false,
  "no-header": false,
  "N": false,
  "noHeader": false,
  "verbose": true,
  "v": true,
  "format": "csv",
  "f": "csv",
  "start": "1921-10",
  "s": "1921-10",
  "stop": "1922-10",
  "t": "1922-10",
  "ts": ".",
  "S": ".",
  "to": "linksWY1922",
  "T": "linksWY1922",
  "max-ub": 1000000000000,
  "M": 1000000000000,
  "maxUb": 1000000000000,
  "debug": "all",
  "D": "all",
  "fs": ",",
  "F": ",",
  "config": "C:\\Users\\Mahesh",
  "c": "C:\\Users\\Mahesh",
  "$0": "C:\\Users\\Mahesh\\AppData\\Roaming\\npm\\node_modules\\calvin-network-tools\\bin\\cli.js",
  "data": "C:\\Users\\Mahesh\\Documents\\maskeyGitHub\\calvin-network-data\\data",
  "nodes": [
    "EXT_SAC",
    "HGR08"
  ],
  "runtime": "C:\\Users\\Mahesh\\AppData\\Roaming\\npm\\node_modules\\calvin-network-tools\\HEC_Runtime"
}
**********************

Running matrix command.

Subnet:  ["EXT_SAC","HGR08","EXT_SAC-HGR08"]
removing: CN5
removing: CN4
removing: CN3
removing: CN1
C:\Users\Mahesh\AppData\Roaming\npm\node_modules\calvin-network-tools\nodejs\matrix\utils\split.js:7
    if(id === network.edge.out[i].properties.hobbes.id) {
                                  ^

TypeError: Cannot read property 'properties' of undefined
    at Object.isInbound (C:\Users\Mahesh\AppData\Roaming\npm\node_modules\calvin-network-tools\nodejs\matrix\utils\split.js:7:35)
    at module.exports (C:\Users\Mahesh\AppData\Roaming\npm\node_modules\calvin-network-tools\nodejs\matrix\link.js:40:16)
    at C:\Users\Mahesh\AppData\Roaming\npm\node_modules\calvin-network-tools\nodejs\matrix\index.js:110:22
    at Array.forEach (<anonymous>)
    at onSubnetReady (C:\Users\Mahesh\AppData\Roaming\npm\node_modules\calvin-network-tools\nodejs\matrix\index.js:103:13)
    at C:\Users\Mahesh\AppData\Roaming\npm\node_modules\calvin-network-tools\nodejs\matrix\index.js:78:7
    at C:\Users\Mahesh\AppData\Roaming\npm\node_modules\calvin-network-tools\nodejs\matrix\utils\expand.js:31:8
    at C:\Users\Mahesh\AppData\Roaming\npm\node_modules\calvin-network-tools\node_modules\async\lib\async.js:52:16
    at C:\Users\Mahesh\AppData\Roaming\npm\node_modules\calvin-network-tools\node_modules\async\lib\async.js:269:32
    at C:\Users\Mahesh\AppData\Roaming\npm\node_modules\calvin-network-tools\node_modules\async\lib\async.js:44:16

```
Your time is really appreciated.
Thanks

**Comment by msdogan** [comment]
Hi @mlmaskey,
I was able to export following matrix `(base) C:\Users\PC\Desktop>cnf matrix --format csv --start 1921-10 --stop 1922-10 --ts . --to linksWY1922 --max-ub 1000000000000 --debug all --verbose D17 SR_FOL D9 C173 HGP08 A207 CVPM08G HGR08 GW_08 CVPM08S HSU207C173 HU207 HSD207 WTP207 U207 D517 C107 D85 D64 C67 HSU204C67 HGP07 HGR07 GW_07 C7C8 C104 C105 D44 D503 D511 D513 D55 D509 HXI204 HNP204 HP204 HSD204 HSU204C67 HU204 WTP204 WWP204 U204 EXT_SAC INT_SAC`

I believe problem is not with HGR08. I excluded Ag CVPM07 as it gets water from Bear and Feather Rivers. I believe you want to explore recharge opportunities for GW08, which Ag CVPM07 should not significantly affect. I saw you also included some Yolo Bypass nodes and Cache Creek nodes, which also should not affect GW08 operations. Check the nodes above and add other nodes you like.

**Comment by mlmaskey** [comment]
@msdogan I fixed the issues regarding this. Sorry for the late information. However, I am also being able to make a regional model of Folsom lake. Please look at them in my repository mlmaskey/calvin-network-data. Here you will find several versions. Also, I reframed the variant of the CALVIN model for the regional and cookie-cut version. I hope @nickrsan  have already knew that as well.
Thanks for the reply.
