### ISSUE TITLE
Initialization Mode (Add QI Parameters)

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/calvin-network-tools#8]
When running the build script, there should be the --initialize and --no-initialize option.  The default should be --initialize.  When this is in place, the PRI file is iniitialized with our best guess at  the flow through all the links ( And the Storage units)
- [ ] For example, Note the addition of QI to the storage node.  This is the data from the 'storage.csv` file, cut to the proper start and stop dates.  
- [ ] I'm not sure about the A= parameter.  Either we pass it in as in --A=  or --initialize=PARM_A

```
quinn@cws-quinn:~/HEC$ node ~/calvin-network-tools/nodejs/prm show --data ~/calvin-network-data/data --initialize=foo SR_SHA 
..
..        ***** NODE DEFINITIONS *****
..
NODE      SR_SHA      2496.000    0.0065  3699.320
ND        Shasta Lake                                                           
..
..        ***** INFLOW DEFINITIONS *****
..
LINK      INFLOW    SOURCE    SR_SHA    1.000     0.000                                   
LD                                                                                        
IN        A= B=SR_SHA C=FLOW_LOC(KAF) D= E=1MON F=default

..
..        ***** STORAGE LINK DEFINITIONS *****
..
LINK      RSTO      SR_SHA    SR_SHA    1.000                                             
LD        Shasta Lake                                                                     
QL        A= B=SR_SHA C=STOR_LBT(KAF) D= E=1MON F=
BU        3828,4042,4330,4552,4552,4552,4300,4000,3700,3400,3252,3368
EV        A= B=SR_SHA C=EVAP_RATE(FT) D= E=1MON F=
EAC       A= B=SR_SHA C=EL-AR-CAP D= E= F=
PS        MO=JAN A= B=SR_SHA C=Q(KAF)-P_EDT D= E=JAN F=
...
PS        MO=DEC A= B=SR_SHA C=Q(KAF)-P_EDT D= E=DEC F=
QI        A=S09I04 B=SR_SHA C=STOR D= E=1MON F= 
..

```
- [ ] Link Definitions

Here we use the flow.csv file from the link cut to the appropriate times.

```
quinn@cws-quinn:~/HEC$ node ~/calvin-network-tools/nodejs/prm show --data ~/calvin-network-data/data - -initialize=foo SR_SHA-D5
..        ***** LINK DEFINITIONS *****
..
LINK      DIVR      SR_SHA    D5        1.0000                                            
LD        Sacramento River between Shasta Dam and Keswick Reservoir                       
PQ        MO=JAN A= B=SR_SHA-D5 C=Q(KAF)-P_EDT D= E=JAN F=
...
PQ        MO=DEC A= B=SR_SHA-D5 C=Q(KAF)-P_EDT D= E=DEC F=
QI        A=S09I04 B=SR_SHA-D5 C=FLOW_DIV(KAF) D= E=1MON F= 
```

**Comment by jrmerz** [comment]
@qjhart give it a go.  --initialize is inferred.  If no value is passed to --initialize, 'init' is used in the A parameter.  otherwise do something like '--initialize foo'.  All dates obey --start / --stop.

I did add a small fix for --stop.  Before if you passed --stop 2002-12, the date 2002-12-01 was used.  Now the end of the month will be used, 2002-12-31.  This obviously is not used for the start date.

I will leave it to you to close.

**Comment by qjhart** [comment]
Looks good
